site_name: Challenge DevOps
theme:
  name: mkdocs #windmill mkdocs, readthedocs, material
copyright: 'Challenge DevOps Team'
site_author: 'Challenge DevOps Team'
site_description: 'Challenge DevOps Documentation'
use_directory_urls: false
markdown_extensions:
  # - pymdownx.snippets
  # - pymdownx.superfences
  # - pymdownx.inlinehilite
  - admonition
  # - pymdownx.details
  - codehilite
  - attr_list
  - md_in_html
plugins:
    - search
    # - glightbox
    # - markdownextradata
nav:
  - About Us: index.md
  - Code Rendering Types[15/04/24]:
    - concept: rendering/concept.md
    - CSR: rendering/CSR.md
    - SSR: rendering/SSR.md
    - SSG: rendering/SSG.md
    - ISR: rendering/ISR.md
