site_name: Challenge DevOps
theme:
  name: readthedocs #windmill mkdocs, readthedocs, material
copyright: 'Challenge DevOps Team'
site_author: 'Challenge DevOps Team'
site_description: 'Challenge DevOps Documentation'
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
plugins:
    - search
nav:
  - About Us: index.md
  - Code Rendering Types:
    - rendering/concept.md
    - rendering/CSR.md
    - rendering/SSR.md
    - rendering/SSG.md
    - rendering/ISR.md
  - Docker:
    - Dockercompose: docker/docker.md
  #   - Docker networking: rendering/concept.md
  #   - volumes: rendering/concept.md
  #   - Environment variables: rendering/concept.md
  # - Terraform:
  #   - functions: rendering/concept.md
  #   - loops: rendering/concept.md
  #   - variables: rendering/concept.md
  # - Kubernetes:
  # - Proxy:
  - Golang:
    - learning:
      - golang/learning/func-breakdown.md
      - golang/learning/pointers-dereferencing.md
      - golang/learning/methods.md
      - golang/learning/struct.md
      - golang/learning/file-operations.md
      - golang/learning/complex-struct.md
      - golang/learning/database-struct.md
      - golang/learning/db-connection.md
      - golang/learning/db-crud.md
      - golang/learning/json.md
      - golang/learning/yaml.md
    - projects:
      - golang/projects/1-Simple-CLI-Tool.md
      - golang/projects/2-Web-Server-with-Basic-API.md
      - golang/projects/3-Simple-Monitoring-Script.md
      - golang/projects/4-Container-Image-Builder.md
      - golang/projects/5-Simple-Chat-Server.md
      - golang/projects/6-Data-Processing-Script.md
      - golang/projects/7-color-print-message.md
  - Bash-Scripting:
    - learning:
      - bash/learning/special-variable.md
      - bash/learning/conditional-expression.md
      - bash/learning/jq.md
      - bash/learning/yq.md
    - projects:
      - bash/projects/1-File-Organizer.md
      - bash/projects/2-System-Monitor.md
      - bash/projects/3-Backup-Script.md
      - bash/projects/4-Web-Log-Analyzer.md
      - bash/projects/5-Task-Scheduler.md
      - bash/projects/6-color-print-message.md
  # - Monitoring:
  # - Logging:
