site_name: Challenge DevOps
theme:
  name: material #windmill mkdocs, readthedocs, material
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
copyright: 'Challenge DevOps Team'
site_author: 'Challenge DevOps Team'
site_description: 'Challenge DevOps Documentation'
use_directory_urls: false
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      title: Table of Contents
      permalink: true
plugins:
  - search
extra_css:
  - stylesheets/extra.css
nav:
  - About Us: index.md
  - Code Rendering Types:
    - rendering/concept.md
    - rendering/CSR.md
    - rendering/SSR.md
    - rendering/SSG.md
    - rendering/ISR.md
  # - Docker:
  #   - Dockercompose: docker/docker.md
  #   - Docker networking: rendering/concept.md
  #   - volumes: rendering/concept.md
  #   - Environment variables: rendering/concept.md
  # - Terraform:
  #   - functions: rendering/concept.md
  #   - loops: rendering/concept.md
  #   - variables: rendering/concept.md
  - Kubernetes:
      - learning:
        - kubernetes/learning/kubernetes.md
        - kubernetes/learning/ingress-controller.md
        - kubernetes/learning/deployment.md
        - kubernetes/learning/service.md
        - kubernetes/learning/networking.md
        - kubernetes/learning/ingress.md
        - kubernetes/learning/configmap-secret.md
        - kubernetes/learning/volumes.md
        - kubernetes/learning/scheduling.md
  - Networking:
      - learning:
        - networking/learning/networking-overview.md
        - networking/learning/important-commands.md
        - networking/learning/traceroute.md
        - networking/learning/netstat.md
        - networking/learning/nslookup-dig.md
        - networking/learning/ssh.md
        - networking/learning/telnet.md
        - networking/learning/nmap.md
        - networking/learning/curl-wget.md
      - projects:
        - networking/projects/1-Setting-Up-a-Secure-VPN.md
  - Proxies:
      - learning:
        - proxies/learning/overview.md
        - proxies/learning/openresty.md
      - projects:
        - proxies/projects/1-nginx-reverse-proxy.md
        - proxies/projects/2-nginx-load-balancing.md
        - proxies/projects/3-multiple-web-server.md
        - proxies/projects/4-redirect.md
        - proxies/projects/5-rewrite.md
  - Ansible:
    - learning:
      - ansible/learning/1-overview.md
      - ansible/learning/2-basic.md
      - ansible/learning/3-ansible-features.md
    - projects:
      - ansible/projects/1-Web-Server-nginx.md
      - ansible/projects/2-Managing-System-Packages.md
      - ansible/projects/3-Configuring-a-Firewall.md
      - ansible/projects/4-Web-App-Using-Docker.md
      - ansible/projects/5-run-nginx-container.md
  - Golang:
    - learning:
      - golang/learning/important-packages.md
      - golang/learning/func-breakdown.md
      - golang/learning/pointers-dereferencing.md
      - golang/learning/methods.md
      - golang/learning/struct.md
      - golang/learning/interface.md
      - golang/learning/interface-ex-2.md
      - golang/learning/pointers.md
      - golang/learning/goroutines.md
      - golang/learning/channels.md
      - golang/learning/file-operations.md
      - golang/learning/complex-struct.md
      - golang/learning/database-struct.md
      - golang/learning/db-connection.md
      - golang/learning/db-crud.md
      - golang/learning/json.md
      - golang/learning/yaml.md
      - golang/learning/os-package.md
      - golang/learning/os-exec.md
      - golang/learning/defer.md
      - golang/learning/path-filepath.md
      - golang/learning/encoding-json.md
      - golang/learning/net-http.md
      - golang/learning/strconv.md
      - golang/learning/context.md
      - golang/learning/strings.md
    - projects:
      - golang/projects/1-Simple-CLI-Tool.md
      - golang/projects/2-Web-Server-with-Basic-API.md
      # - golang/projects/3-Simple-Monitoring-Script.md
      - golang/projects/4-Container-Image-Builder.md
      # - golang/projects/5-Simple-Chat-Server.md
      # - golang/projects/6-Data-Processing-Script.md
      - golang/projects/7-color-print-message.md
      - golang/projects/8-Currency-Conversion-API.md
      - golang/projects/9.Todo-List-API.md
      - golang/projects/10-Recipe-API.md
      - golang/projects/11-contact-list-csv.md
      - golang/projects/12-mongodb-manual.md
      - golang/projects/13-mongoDB-API.md
      - golang/projects/14-midleware-okta.md
  - Bash-Scripting:
    - learning:
      - bash/learning/special-variable.md
      - bash/learning/conditional-expression.md
      - bash/learning/jq.md
      - bash/learning/yq.md
    - projects:
      - bash/projects/1-File-Organizer.md
      - bash/projects/2-System-Monitor.md
      - bash/projects/3-Backup-Script.md
      - bash/projects/4-Web-Log-Analyzer.md
      - bash/projects/5-Task-Scheduler.md
      - bash/projects/6-color-print-message.md
  - miscellaneous:
      - misc/CSP.md
      - misc/CORS.md
      - misc/Authentication-Authorization.md
      - misc/Encryption-Cryptography.md
      - misc/SSL-TLS.md
      - misc/HTTP-Security-Headers.md
      - misc/okta.md
      - misc/OWASP.md
      - misc/Session-Management.md
      - misc/API-Security.md
      
  # - Monitoring:
  # - Logging:
