site_name: Challenge DevOps
theme:
  name: readthedocs #windmill mkdocs, readthedocs, material
copyright: 'Challenge DevOps Team'
site_author: 'Challenge DevOps Team'
site_description: 'Challenge DevOps Documentation'
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
plugins:
    - search
nav:
  - About Us: index.md
  - Code Rendering Types:
    - concept: rendering/concept.md
    - CSR: rendering/CSR.md
    - SSR: rendering/SSR.md
    - SSG: rendering/SSG.md
    - ISR: rendering/ISR.md
  - Docker:
    - Dockercompose: docker/docker.md
  #   - Docker networking: rendering/concept.md
  #   - volumes: rendering/concept.md
  #   - Environment variables: rendering/concept.md
  # - Terraform:
  #   - functions: rendering/concept.md
  #   - loops: rendering/concept.md
  #   - variables: rendering/concept.md
  # - Kubernetes:
  # - Proxy:
  # - Golang:s
  - Bash-Scripting: 
      - bash/special-variable.md
  # - Monitoring:
  # - Logging:
