site_name: Challenge DevOps
theme:
  name: readthedocs #windmill mkdocs, readthedocs, material
copyright: 'Challenge DevOps Team'
site_author: 'Challenge DevOps Team'
site_description: 'Challenge DevOps Documentation'
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
plugins:
    - search
nav:
  - About Us: index.md
  - Code Rendering Types:
    - concept: rendering/concept.md
    - CSR: rendering/CSR.md
    - SSR: rendering/SSR.md
    - SSG: rendering/SSG.md
    - ISR: rendering/ISR.md
  - Docker:
    - Dockercompose: docker/docker.md
  #   - Docker networking: rendering/concept.md
  #   - volumes: rendering/concept.md
  #   - Environment variables: rendering/concept.md
  # - Terraform:
  #   - functions: rendering/concept.md
  #   - loops: rendering/concept.md
  #   - variables: rendering/concept.md
  # - Kubernetes:
  # - Proxy:
  - Golang:
      - golang/func-breakdown.md
      - golang/pointers-dereferencing.md
      - golang/methods.md
      - golang/struct.md
      - golang/file-operations.md
      - golang/complex-struct.md
      - golang/database-struct.md
      - golang/db-connection.md
      - golang/db-crud.md
      - golang/json.md
      - projects:
        - golang/projects/1-Simple-CLI-Tool.md
        - golang/projects/2-Web-Server-with-Basic-API.md
        - golang/projects/3-Simple-Monitoring-Script.md
        - golang/projects/4-Container-Image-Builder.md
        - golang/projects/5-Simple-Chat-Server.md
        - golang/projects/6-Data-Processing-Script.md
        - golang/projects/7-color-print-message.md
  - Bash-Scripting:
      - bash/special-variable.md
      - bash/conditional-expression.md
      - bash/jq.md
      - bash/yq.md
  # - Monitoring:
  # - Logging:
